version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: readwise
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: