version: '3.8'

services:
    mysql:
        image: mysql:latest
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: dima94dimix@MySQL
            MYSQL_USER: root
            MYSQL_DATABASE: readwise
        ports:
            - '3306:3306'
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
