version: '3.1'

services:
    db:
        image: postgres:16
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: user-management
            PGDATA: /var/lib/postgresql/data/
        ports:
            - '5432:5432'
        volumes:
            - db:/var/lib/postgresql/data/

    redis:
        image: redis:latest
        restart: always
        ports:
            - '6379:6379'

volumes:
    db:
