version: '3.8'

services:
    mysql:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: dima94MYSQL
            MYSQL_DATABASE: readwise
        ports:
            - '3007:3306'
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
